dataset:
  dataset_name: InfiniteChoice                                  # or InfiniteQALoader, NovelQA.
  dataset_path: ./data/InfiniteBench/longbook_choice_eng.jsonl  # path to your dataset path. 
  # or NovelQA: ./data/NovelQA
  # or InfiniteQALoader: ./data/InfiniteBench/longbook_qa_eng.jsonl

llm:
  llm_name: Qwen2.5-0.5B-Instruct  # Qwen2.5-7B-Instruct
  llm_path: Qwen2.5-0.5B-Instruct/  # path to your llm model.
  llm_device: cpu                  # device to run the llm.

paths:
  log_path: ./log             # path to save the log.
  answer_path: ./answer/test  # path to save the answer. no need to identify the dataset, they will be automatically saved in corresponding folder.
  cache_path: ./cache/test    # path to save the cache.

cluster:
  length: 1200  # length of each chunk.
  overlap: 100  # overlap of each chunk.
  merge_num: 5  # number of chunks to merge.

resume:
  resumeIndex: 0  # index of the resume.

retriever:
  kwargs:
    device: cpu                      # device to run the retriever.
    shortest_path_k: 4                # number of shortest path to retrieve. 
    debug: True                       # whether to print the debug information.
    merge_num: 5                      # number of chunks to merge.
    overlap: 100                      # overlap of each chunk.
    tokenizer: Qwen2.5-0.5B-Instruct/ # path to your tokenizer.
    max_chunk_setting: 25             # max number of chunks to retrieve.
